### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by adityaparab** [adityaparab/ghdb#8]
Title says it all.

What needs to be explained in the README?

Problem-
Finding a free json based database host can be trouble. There are restrictions and/or limitations in terms of bandwidth, data storage etc. Even if one finds such provider it involves creating new account and remembering an additional password. Free tier accounts have most features disabled and thus are not very friendly towards beginners who say `I don't care about the rest I just want this simple data to be persisted`

Solution:
This project solves these problem by using github repo to store database. Data is persisted on both remote and local repository.
There is a server that abstracts away data manipulation logic between github and the user.
The user provides data along with name of the collection in the database, and the server does appropriate operation based on METHOD of rest api request.
The server manipulates local repo database and periodically commits the database updated to the remote repo.

How to use:
Will be added once the MVP is complete

**Comment by Showndarya** [comment]
Hey @adityaparab 

I will work on this.

**Comment by adityaparab** [comment]
@Showndarya Thank you for helping.
The name of the project as I see now is `ghdb`, which is an acronym I made up for `Github as a Database`. Feel free to suggest if you find something catchy.

**Comment by adityaparab** [comment]
Thank you @Showndarya
