### ISSUE TITLE
Create CONTRIBUTING file

### ISSUE THREAD

**Issue by adityaparab** [adityaparab/ghdb#9]
Title says it all.

**Comment by cnuis2cool** [comment]
Will do. As no description provided for the project, will add empty file.

**Comment by adityaparab** [comment]
Thanks @cnuis2cool 
Please submit PR. Will it be possible for you to add content to the file after I provide more details? I'll be posting what should go into it here in an hour or so. I need help with expanding those points in detail.

**Comment by adityaparab** [comment]
Things to be added to contributing file

- Standard things like fork this repo, clone your fork
- Branch naming conventions - Each issue has a Label. the branch name should begin with <first-label>/short-description-of-issue. Branch name should be in lowercase.
For example if the issue title is `add unit test cases` and has labels `Feature`, `enhancement`, `help wanted` in this order, the name of the branch should be `feature/add-unit-tests`
